### ISSUE TITLE
RigidBody2D: on_body_entered not reporting collisions properly 

### ISSUE THREAD

**Issue by SirLich** [appsinacup/godot-box2d#81]
**Describe the bug**
Compared to GODOT physics, Bod2D is missing a lot of collisions. Here are my solver settings:

![image](https://github.com/appsinacup/godot-box2d/assets/18729296/a67fa4bc-5a27-4812-b64f-eea5f1a23722)

The use-case was re-creating https://www.wikiwand.com/en/Suika_Game, for fun. So I'm essentially bouncing around some balls, and then combining them when they touch.

**To Reproduce**
1. Create a two RigidBody2D spheres, one laying on the ground, one dropped from some height.
2. Connect the `on_body_entered` signal, and print some debugging string
3. Observe that around 50% of collisions won't be reported

**Expected behavior**
Collisions between RigidBody2D should always send `on_body_entered` signal, assuming `moniter` is set to true.

**Project**
If applicable, add a reproducible project to help explain your problem.

**Versions (please complete the following information):**
 - OS: Windows
 - Godot 4.2 Stable
 - Box2d v0.9.2

**Comment by Ughuuu** [comment]
Could you upload a test project also?
Can you also use the latest build(not one from asset store, that one might be old). There was a similar issue to this that was fixed recently on main branch. Can you give that a try?

**Comment by SirLich** [comment]
Yes, here is a test-project. Explanation: This is a quick prototype of Suika Game as I mentioned. Right-click to drop a ball. Two balls should combine. Here is an example setup which didn't work:

![image](https://github.com/appsinacup/godot-box2d/assets/18729296/15395456-5006-47c6-a148-9782bf5f985f)
And here is the project:

[fruit_rolls.zip](https://github.com/appsinacup/godot-box2d/files/13536117/fruit_rolls.zip)

I will try with latest from github too.

**Comment by SirLich** [comment]
OK so I installed 0.9.3 from this link: https://github.com/appsinacup/godot-box2d/releases/tag/v0.9.3, but `VERSION.txt` inside of the installation is calling it `0.9.5.`. In either case, the issue still persists.

**Comment by SirLich** [comment]
As a test, I also doubled all relevant physics options:
 - `Box2D/Velocity Iterations` 8 -> 16
 - `Box2D/Position Iterations` 3 -> 6
 - `PhysicsTicksPerSecton` -> 60 -> 120
 - `Max Physics Steps per Frame` 8 -> 32

And I tried setting jitter-fix to both 0 and 1

**Comment by Ughuuu** [comment]
The jitter fix doesnt do anything for box2d. Thanks gor detailed bug report.

**Comment by Ughuuu** [comment]
Can you try this one also: https://github.com/appsinacup/godot-box2d/actions/runs/7045170933

**Comment by SirLich** [comment]
I am INCREDIBLY impressed. This version works a charm, at least in the simple cases. I also noticed that integrated Godot physics can start floundering, once I have enough collisions going on. I didn't stress test Box2D yet, but it seems at least as stable as integrated physics, and it's much less jittery. 

Thanks for the help!

**Comment by SirLich** [comment]
![image](https://github.com/appsinacup/godot-box2d/assets/18729296/e14318ba-8d6e-4a69-ac92-fca205f000a4)

In more intense situations I can get it to trip up, but I admit this might be my code at fault. My assumption was that `on_body_entered` would be called for BOTH bodies, which is why I used a system which waited for the same collision pair to be reported twice (sum of RID Ids). 

I admit this logic may be faulty. In this photo you can see collisions being reported on the two three parrots, but they're not combining.

**Comment by Ughuuu** [comment]
Interesting. Does godot also return for both bodies?(I would assume so). It could be a bug still that on_body_entered is not called for both bodies. If godot does so I can investigate why box2d doesnt.

**Comment by SirLich** [comment]
Both Godot integrated, and Box2D seems to break down at some large-enough scale, even when setting total monitored bodies to something high enough (e.g., 20). 

The latest patch is MUCH more stable, and I would surmise has brought the behavior in-line with Godot integrated, but not necessarily better. 

I will do some debugging on my side and see if I can identify the issue. If not (or I can pin it on physics), I will send a new, simpler reproduction which can create the issue.

**Comment by SirLich** [comment]
I identified the issue. It occurs when I'm spawning the object, and it "enters" into another objects space. In that case, the physics bodies are recalculated (so they're not overlapping), but the delegate isn't called.

**Comment by SirLich** [comment]
My solution: I start with size of the collider at 0, and then tween it to the desired size, in 0.1 seconds. This solves the issue from my side. If you're happy with that, then this issue can be closed as completed (based on the version you built for me). 

Many thanks!

**Comment by Ughuuu** [comment]
Does this also happen in godot in same way? Sounds a little complicated, so the use case is that sometimes when you change the collider size(eg from 2 to 4) it doesnt generate collision event?

**Comment by SirLich** [comment]
It seems to be consistent between Box2D and Godot, after your patch.
